FROM nvidia/cuda:9.0-devel-ubuntu16.04

ENV CUDNN_VERSION=7.0.5.15-1+cuda9.0

RUN echo "deb http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list

RUN apt-get update && apt-get install -y --no-install-recommends --allow-downgrades --allow-change-held-packages \
		apt-transport-https \
		apt-utils \
        build-essential \
        ca-certificates \
        cmake \
        curl \
        g++ \
        git \
        libcudnn7=${CUDNN_VERSION} \
        libjpeg-dev \
        libpng-dev \
        locales \
        software-properties-common \
        tmux \
        unzip \
        wget

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

SHELL ["/bin/bash", "-c"]

COPY conda_requirements.txt .
RUN conda install --yes \
    -c conda-forge \
    -c pytorch \
    -c menpo \
    --file conda_requirements.txt \
	&& conda clean -tipsy

COPY requirements.txt .
RUN pip install -r requirements.txt

# install pycocotools
RUN git clone https://github.com/cocodataset/cocoapi.git \
 && cd cocoapi/PythonAPI \
 && python setup.py build_ext install

# install maskrcnn
RUN git clone https://github.com/facebookresearch/maskrcnn-benchmark.git \
 && cd maskrcnn-benchmark \
# && git reset --hard 75523a75312a7c8a9a007f75375f6310b8d37ad9 \
 && sed -i -e 's/torch.cuda.is_available()/True/g' setup.py \
 && python setup.py build develop \
 && sed -i -e 's/True/torch.cuda.is_available()/g' setup.py

COPY tmux.conf /root/.tmux.conf
WORKDIR /workspace
CMD /bin/bash